### ISSUE TITLE
Feature Request: provide a millis function

### ISSUE THREAD

**Issue by dvberkel** [Jewelbots/arduino-library#24]
I was working on a project fully expecting to be able to call [`millis`](https://www.arduino.cc/en/Reference/Millis), a function that

>  the number of milliseconds since the Arduino board began running the current program.

Unfortunately the code does not compile because 

```
error: 'millis' was not declared in this scope
``` 

It would be great if the `millis` function would be provided as a function.

**Comment by dvberkel** [comment]
I have studied the code base a bit and I am fairly confident that this is feasible. I would like to share my thoughts on how this could be implemented, getting some feedback if it could work and how it can be improved.

As for the API, I would suggest extending the [`Timer.h`](https://github.com/Jewelbots/arduino-library/blob/master/jewelbots_nRF51822_board_v100/cores/JWB_nRF51822/Timer.h) header with

```cpp
uint32_t millis(void);
```

The implementation in [`Timer.cpp`](https://github.com/Jewelbots/arduino-library/blob/master/jewelbots_nRF51822_board_v100/cores/JWB_nRF51822/Timer.cpp) would consist of a call to `app_timer_cnt_get` from [`app_timer.h`](https://github.com/Jewelbots/arduino-library/blob/master/jewelbots_nRF51822_board_v100/cores/JWB_nRF51822/ble-nrf51822-master/source/nordic_sdk/components/libraries/timer/app_timer.h), dividing the result by the `APP_TIMER_CLOCK_FREQ` in order to convert to milliseconds.

If this sound good, I am willing to provide a pull request implementing this feature.

**Comment by davison-sm** [comment]
Ok, just pushed the feature.  In the Board Manager you should have the option to update the Jewelbots Arduino Library to v1.0.1 which contains the function (runtime_ms).  Ended up being simple, but took a bit of research to reassure myself it would work together with everything else.

A quick note that tripped me up, since the original definition is runtime since the program began that is what I implemented in the code.  The timer starts as early in the bootup sequence as possible and I immediately grab a time value at that point to use as the starting point.  But after it grabs that value the vibration motor calibrates and the led startup sequence goes, so the value of runtime when the code inside your setup or loop functions start may be later than would be expected.

Thanks again for your interest in Jewelbots!  Please let me know if this works for you and maybe you could share a bit about what you are building on our forums (community.jewelbots.com).
